In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('benssesdec.xlsx')

In [3]:
df.head(10)

,Item,Plaqueta,Unnamed: 2,Tombo,Descrição,Nº DE SÉRIE,DEPARTAMENTO,SETOR,SALA,Estado de Conservação,Unnamed: 10,Unnamed: 11,Unnamed: 12,Classificação,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,Sim,Não,NaN,NaN,NaN,NaN,NaN,NaN,Excelente,Bom,Regular,Péssimo,Servivel,Inservível,Ocioso,Recuperavel,Antieconomico,Irrecuperável
1,1,X,NaN,25423,ACESSORIO:PERSIANA HORIZONTAL 16MM COM COMANDO...,000000,PVH- UNISP LESTE,PM,GUARDA,NaN,NaN,X,NaN,X,NaN,NaN,NaN,NaN,NaN
2,9,X,NaN,59781,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,000000,ALVORADA D'OESTE- UNISP,BOMBEIRO,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
3,17,X,NaN,59701,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,000000,JI- PARANA- UNISP,DAT,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
4,18,X,NaN,59702,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,000000,JI- PARANA- UNISP,DIRETOR DAT,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
5,19,X,NaN,59703,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,000000,JI- PARANA- UNISP,SUB COMANDO PM,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
6,20,X,NaN,59705,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,000000,JI- PARANA- UNISP,SARGENTEAÇÃO,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
7,21,X,NaN,59706,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,000000,JI- PARANA- UNISP,P3 SEÇÃO OPERACIONAL,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
8,22,X,NaN,59707,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,000000,JI- PARANA- UNISP,NUCLEO DE INTELIGENCIA DA PM,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
9,23,X,NaN,59708,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,000000,JI- PARANA- UNISP,GABINETE DELEGADO REGIONAL,NaN,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN

In [4]:
df.loc[(df["DEPARTAMENTO"]=="JI- PARANA- UNISP"), ['DEPARTAMENTO', 'Descrição', 'Tombo']]

,DEPARTAMENTO,Descrição,Tombo
3,JI- PARANA- UNISP,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,59701
4,JI- PARANA- UNISP,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,59702
5,JI- PARANA- UNISP,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,59703
6,JI- PARANA- UNISP,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,59705
7,JI- PARANA- UNISP,AMARIO ALTO DIMENSOES 800X500X1600MM NA COR CA...,59706
...,...,...,...
11646,JI- PARANA- UNISP,"SWITCH 24 PORTAS,10/100MBITS,GERENCIAVEL/3COM/...",18579
11647,JI- PARANA- UNISP,"SWITCH 24 PORTAS,10/100MBITS,GERENCIAVEL/3COM/...",18597
11650,JI- PARANA- UNISP,"SWITCH 24 PORTAS,10/100MBITS,GERENCIAVEL/EDIMA...",18477
11655,JI- PARANA- UNISP,SWITCH DE 24 PORTAS 10/100 MBITS/TRELLIS/SWT-24X,8488
11732,JI- PARANA- UNISP,TV LED FULL HD SMART 43 POLEGADAS/PHILIPS/43PF...,57284

In [5]:
def toexcel(departamento):
    colunas = ['DEPARTAMENTO', 'Descrição', 'Tombo']
    filter = df.loc[(df['DEPARTAMENTO']==departamento), colunas]
    filter.to_excel(f'{departamento}.xlsx',  index = False, header=True)

In [6]:
toexcel('JI- PARANA- UNISP')